version: '3'

services:
  let-me-ask-api:
    build: .
    ports:
      - '3333:3333'
    depends_on:
      pgvector:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: sh -c "npm run db:migrate && npm run db:seed && npm start"

  pgvector:
    image: pgvector/pgvector:pg17
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=let-me-ask
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker -d let-me-ask']
      interval: 5s
      timeout: 5s
      retries: 5
