name: Migrate & Seed Database

on:
  push:
    branches:
      - main

jobs:
  migrate-and-seed:
    name: Run migrations & seeds
    runs-on: ubuntu-24.04
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate Drizzle types (opcional)
        run: npm run db:generate

      - name: Run Drizzle migrations
        run: npm run db:migrate

      - name: Seed database
        run: npm run db:seed
